/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    coaches: Coach;
    media: Media;
    pages: Page;
    teams: Team;
    users: User;
    redirects: Redirect;
  };
  globals: {
    footer: Footer;
    'main-menu': MainMenu;
  };
}
export interface Coach {
  id: string;
  name: string;
  headshot: string | Media;
  Role?: {
    title?: string;
    roles?: {
      role: string;
      id?: string;
    }[];
  };
  socials?: {
    twitter?: string;
    instagram?: string;
    facebook?: string;
    youtube?: string;
  };
  biography?: {
    [k: string]: unknown;
  }[];
  career?: {
    achievement: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Media {
  id: string;
  alt: string;
  darkModeFallback?: string | Media;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Page {
  id: string;
  title: string;
  hero?: {
    previewTest?: string;
  };
  slug?: string;
  parent?: string | Page;
  breadcrumbs?: {
    doc?: string | Page;
    url?: string;
    label?: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Team {
  id: string;
  name: string;
  coaches?: string[] | Coach[];
  teamPhoto?: string | Media;
  teamsnapId: string;
  roster?: {
    firstName: string;
    lastName: string;
    number?: string;
    positions?: (
      | 'pitcher'
      | 'catcher'
      | 'firstBase'
      | 'secondBase'
      | 'thirdBase'
      | 'shortstop'
      | 'middleInfield'
      | 'cornerInfield'
      | 'infield'
      | 'outfield'
      | 'utility'
    )[];
    homeTown?: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface User {
  id: string;
  name?: string;
  roles?: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Redirect {
  id: string;
  from: string;
  to: {
    type?: 'reference' | 'custom';
    reference: {
      value: string | Page;
      relationTo: 'pages';
    };
    url: string;
  };
  updatedAt: string;
  createdAt: string;
}
export interface Footer {
  id: string;
  socialLinks?: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    github?: string;
  };
  columns?: {
    label?: string;
    navItems?: {
      link: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | Team;
              relationTo: 'teams';
            };
        url: string;
        label: string;
      };
      id?: string;
    }[];
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
export interface MainMenu {
  id: string;
  right?: {
    type?: 'single' | 'dropdown';
    link?: {
      type?: 'reference' | 'custom';
      newTab?: boolean;
      reference:
        | {
            value: string | Page;
            relationTo: 'pages';
          }
        | {
            value: string | Team;
            relationTo: 'teams';
          };
      url: string;
      label: string;
    };
    dropdownItems?: {
      link: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | Team;
              relationTo: 'teams';
            };
        url: string;
        label: string;
        description?: string;
      };
      id?: string;
    }[];
    id?: string;
  }[];
  left?: {
    link: {
      type?: 'reference' | 'custom';
      newTab?: boolean;
      reference:
        | {
            value: string | Page;
            relationTo: 'pages';
          }
        | {
            value: string | Team;
            relationTo: 'teams';
          };
      url: string;
      label: string;
      appearance?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'link';
    };
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
