/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    coaches: Coach;
    media: Media;
    pages: Page;
    pageSettings: PageSetting;
    posts: Post;
    teams: Team;
    teamSnapForms: TeamSnapForm;
    users: User;
    redirects: Redirect;
  };
  globals: {
    'site-settings': SiteSetting;
    footer: Footer;
    header: Header;
  };
}
export interface Coach {
  id: string;
  name: string;
  headshot: string | Media;
  role?: {
    title?: string;
    roles?: {
      role: string;
      id?: string;
    }[];
    joinDate?: number;
  };
  socials?: {
    twitter?: string;
    instagram?: string;
    facebook?: string;
    youtube?: string;
  };
  biography?: {
    [k: string]: unknown;
  }[];
  career?: {
    achievement: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Media {
  id: string;
  alt: string;
  aspectRatio?: '1.7778' | '1.3333' | '1.5' | '1' | '1.25' | '3' | '0.8';
  blurURL?: string;
  darkModeFallback?: string | Media;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Page {
  id: string;
  hero: {
    type: 'default' | 'contentMedia' | 'form' | 'home' | 'registration';
    richText?: {
      [k: string]: unknown;
    }[];
    links?: {
      link: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | PageSetting;
              relationTo: 'pageSettings';
            }
          | {
              value: string | Team;
              relationTo: 'teams';
            };
        url: string;
        label: string;
        appearance?: 'primary' | 'secondary';
      };
      id?: string;
    }[];
    media: string | Media;
    values?: {
      value: string;
      id?: string;
    }[];
    forms?: string[] | TeamSnapForm[];
    previewTest?: string;
  };
  layout?: (
    | {
        contentBackgroundColor?: 'white' | 'primary' | 'shaded' | 'secondary' | 'muted';
        contentFields: {
          columns?: {
            alignment: 'left' | 'center' | 'right';
            width: 'oneThird' | 'half' | 'twoThirds' | 'full';
            richText?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | PageSetting;
                      relationTo: 'pageSettings';
                    }
                  | {
                      value: string | Team;
                      relationTo: 'teams';
                    };
                url: string;
                label: string;
                appearance?: 'primary' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link';
              };
              id?: string;
            }[];
            id?: string;
          }[];
          singleColumn: {
            alignment: 'left' | 'center' | 'right';
            width: 'oneThird' | 'half' | 'twoThirds' | 'full';
            richText?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | PageSetting;
                      relationTo: 'pageSettings';
                    }
                  | {
                      value: string | Team;
                      relationTo: 'teams';
                    };
                url: string;
                label: string;
                appearance?: 'primary' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link';
              };
              id?: string;
            }[];
            id?: string;
          };
        };
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        contentGridBackgroundColor?: 'white' | 'primary' | 'shaded' | 'secondary' | 'muted';
        contentGridFields: {
          useLeadingHeader?: boolean;
          leadingHeader?: {
            [k: string]: unknown;
          }[];
          alignment: 'start' | 'center' | 'end';
          columns?: {
            width: 'oneThird' | 'half' | 'twoThirds' | 'full';
            content?: (
              | {
                  contentFields?: {
                    columns?: {
                      richText?: {
                        [k: string]: unknown;
                      }[];
                      links?: {
                        link: {
                          type?: 'reference' | 'custom';
                          newTab?: boolean;
                          reference:
                            | {
                                value: string | Page;
                                relationTo: 'pages';
                              }
                            | {
                                value: string | PageSetting;
                                relationTo: 'pageSettings';
                              }
                            | {
                                value: string | Team;
                                relationTo: 'teams';
                              };
                          url: string;
                          label: string;
                          appearance?: 'primary' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link';
                        };
                        id?: string;
                      }[];
                      id?: string;
                    }[];
                    singleColumn?: {
                      richText?: {
                        [k: string]: unknown;
                      }[];
                      links?: {
                        link: {
                          type?: 'reference' | 'custom';
                          newTab?: boolean;
                          reference:
                            | {
                                value: string | Page;
                                relationTo: 'pages';
                              }
                            | {
                                value: string | PageSetting;
                                relationTo: 'pageSettings';
                              }
                            | {
                                value: string | Team;
                                relationTo: 'teams';
                              };
                          url: string;
                          label: string;
                          appearance?: 'primary' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link';
                        };
                        id?: string;
                      }[];
                      id?: string;
                    };
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'content';
                }
              | {
                  imagesFields: {
                    useLeadingHeader?: boolean;
                    leadingHeader?: {
                      [k: string]: unknown;
                    }[];
                    columns?: '1' | '2' | '3' | '4' | '5';
                    images: string[] | Media[];
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'galleryImages';
                }
              | {
                  mapFields: {
                    /**
                     * @minItems 2
                     * @maxItems 2
                     */
                    map?: [number, number];
                    options: {
                      zoom: number;
                      animation: 'none' | 'rotate';
                    };
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'map';
                }
              | MediaBlock
            )[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'contentGrid';
      }
    | {
        galleryImagesBackgroundColor?: 'white' | 'primary' | 'shaded' | 'secondary' | 'muted';
        imagesFields: {
          useLeadingHeader?: boolean;
          leadingHeader?: {
            [k: string]: unknown;
          }[];
          columns?: '1' | '2' | '3' | '4' | '5';
          images: string[] | Media[];
        };
        id?: string;
        blockName?: string;
        blockType: 'galleryImages';
      }
    | {
        mapBackgroundColor?: 'white' | 'primary' | 'shaded' | 'secondary' | 'muted';
        mapFields: {
          /**
           * @minItems 2
           * @maxItems 2
           */
          map?: [number, number];
          options: {
            zoom: number;
            animation: 'none' | 'rotate';
          };
        };
        id?: string;
        blockName?: string;
        blockType: 'map';
      }
    | MediaBlock
    | {
        postsHighlightBackgroundColor?: 'white' | 'primary' | 'shaded' | 'secondary' | 'muted';
        caseStudiesHighlightFields: {
          useLeadingHeader?: boolean;
          leadingHeader?: {
            [k: string]: unknown;
          }[];
          posts: string[] | Post[];
        };
        id?: string;
        blockName?: string;
        blockType: 'postsHighlight';
      }
    | {
        sliderBackgroundColor?: 'white' | 'primary' | 'shaded' | 'secondary' | 'muted';
        sliderFields: {
          useLeadingHeader?: boolean;
          leadingHeader?: {
            [k: string]: unknown;
          }[];
          sliderType: 'contentSlider' | 'imageSlider' | 'relationshipSlider';
          imageSlides: {
            image: string | Media;
            id?: string;
          }[];
          contentSlides: {
            richText: {
              [k: string]: unknown;
            }[];
            isQuote?: boolean;
            quoteDate: string;
            id?: string;
          }[];
          relationshipSlides:
            | (
                | {
                    value: string;
                    relationTo: 'pages';
                  }
                | {
                    value: string;
                    relationTo: 'pageSettings';
                  }
                | {
                    value: string;
                    relationTo: 'coaches';
                  }
                | {
                    value: string;
                    relationTo: 'teams';
                  }
              )[]
            | (
                | {
                    value: Page;
                    relationTo: 'pages';
                  }
                | {
                    value: PageSetting;
                    relationTo: 'pageSettings';
                  }
                | {
                    value: Coach;
                    relationTo: 'coaches';
                  }
                | {
                    value: Team;
                    relationTo: 'teams';
                  }
              )[];
        };
        id?: string;
        blockName?: string;
        blockType: 'slider';
      }
  )[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
    keywords?: string;
  };
  title: string;
  slug?: string;
  parent?: string | Page;
  breadcrumbs?: {
    doc?: string | Page;
    url?: string;
    label?: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface PageSetting {
  id: string;
  hero: {
    type: 'default' | 'contentMedia' | 'form' | 'home' | 'registration';
    richText?: {
      [k: string]: unknown;
    }[];
    links?: {
      link: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | PageSetting;
              relationTo: 'pageSettings';
            }
          | {
              value: string | Team;
              relationTo: 'teams';
            };
        url: string;
        label: string;
        appearance?: 'primary' | 'secondary';
      };
      id?: string;
    }[];
    media: string | Media;
    values?: {
      value: string;
      id?: string;
    }[];
    forms?: string[] | TeamSnapForm[];
    previewTest?: string;
  };
  coachingStaff?: {
    mainCoaches?: string[] | Coach[];
    subsidaryCoaches?: string[] | Coach[];
  };
  news?: {
    test?: string;
  };
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
    keywords?: string;
  };
  type: 'coachingStaff' | 'news';
  title: string;
  slug?: string;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Team {
  id: string;
  name: string;
  coaches?: string[] | Coach[];
  teamPhoto?: string | Media;
  teamsnapId: string;
  webCalendar?: string;
  roster?: {
    firstName: string;
    lastName: string;
    number?: string;
    positions?: (
      | 'pitcher'
      | 'catcher'
      | 'firstBase'
      | 'secondBase'
      | 'thirdBase'
      | 'shortstop'
      | 'middleInfield'
      | 'cornerInfield'
      | 'infield'
      | 'outfield'
      | 'utility'
    )[];
    homeTown?: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface TeamSnapForm {
  id: string;
  title: string;
  teamSnapId: string;
  description?: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface MediaBlock {
  mediaFields?: {
    embed?: boolean;
    embedVideo?: {
      platform?: 'youtube' | 'vimeo';
      videoID?: string;
      aspectRatio?: '1.7778' | '1.3333' | '1.5' | '1' | '1.25' | '3' | '0.8';
      manualThumbnail?: string | Media;
    };
    internalMedia?: {
      media?: string | Media;
    };
    size?: 'normal' | 'wide' | 'fullscreen';
    caption?: {
      [k: string]: unknown;
    }[];
  };
  id?: string;
  blockName?: string;
  blockType: 'media';
}
export interface Post {
  id: string;
  title: string;
  image: string | Media;
  excerpt?: {
    [k: string]: unknown;
  }[];
  content: (
    | {
        blogContentFields?: {
          richText?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'blogContent';
      }
    | MediaBlock
  )[];
  relatedPosts?: string[] | Post[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
    keywords?: string;
  };
  slug?: string;
  authors: string[] | User[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface User {
  id: string;
  name?: string;
  roles?: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Redirect {
  id: string;
  from: string;
  to: {
    type?: 'reference' | 'custom';
    reference: {
      value: string | Page;
      relationTo: 'pages';
    };
    url: string;
  };
  updatedAt: string;
  createdAt: string;
}
export interface SiteSetting {
  id: string;
  socialLinks?: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    github?: string;
  };
  streetAddress?: string;
  city?: string;
  province?: string;
  postalCode?: string;
  country?: string;
  email?: string;
  phoneNumber?: string;
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
    keywords?: string;
  };
  _status?: 'draft' | 'published';
  updatedAt?: string;
  createdAt?: string;
}
export interface Footer {
  id: string;
  columns?: {
    label?: string;
    navItems?: {
      link: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | PageSetting;
              relationTo: 'pageSettings';
            }
          | {
              value: string | Team;
              relationTo: 'teams';
            };
        url: string;
        label: string;
      };
      id?: string;
    }[];
    id?: string;
  }[];
  _status?: 'draft' | 'published';
  updatedAt?: string;
  createdAt?: string;
}
export interface Header {
  id: string;
  topBar: {
    richText?: {
      [k: string]: unknown;
    }[];
  };
  mainMenu: {
    items: {
      type?: 'single' | 'dropdown';
      label: string;
      link?: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | PageSetting;
              relationTo: 'pageSettings';
            }
          | {
              value: string | Team;
              relationTo: 'teams';
            };
        url: string;
      };
      menu?: {
        blocks?: (
          | {
              menuHighlightMedia?: string | Media;
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | PageSetting;
                      relationTo: 'pageSettings';
                    }
                  | {
                      value: string | Team;
                      relationTo: 'teams';
                    };
                url: string;
                label: string;
                description?: string;
              };
              id?: string;
              blockName?: string;
              blockType: 'menuHighlight';
            }
          | {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | PageSetting;
                      relationTo: 'pageSettings';
                    }
                  | {
                      value: string | Team;
                      relationTo: 'teams';
                    };
                url: string;
                label: string;
                description?: string;
              };
              id?: string;
              blockName?: string;
              blockType: 'menuLink';
            }
          | {
              name?: string;
              links?: {
                link: {
                  type?: 'reference' | 'custom';
                  newTab?: boolean;
                  reference:
                    | {
                        value: string | Page;
                        relationTo: 'pages';
                      }
                    | {
                        value: string | PageSetting;
                        relationTo: 'pageSettings';
                      }
                    | {
                        value: string | Team;
                        relationTo: 'teams';
                      };
                  url: string;
                  label: string;
                };
                id?: string;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'menuColumn';
            }
        )[];
      };
      id?: string;
    }[];
  };
  _status?: 'draft' | 'published';
  updatedAt?: string;
  createdAt?: string;
}
